version: '3'
services:
  web:
    build: .
    ports:
    - "4000:4000"
    command: mix phx.server
    volumes:
    - ./app:/app
    links:
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432"
  initiate:
    build: .
    working_dir: /
    tty: true
    volumes:
      - ./initiate.sh:/initiate.sh
      - ./app:/app
    command: sh ./initiate.sh
